services:
  # app:
  #   image: controle-micro-go
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: controle_micro_go
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: korp
  #     DB_PORT: 5432
  #     DB_SSLMODE: disable
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: korp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
